apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "<YOUR_DROPLET_ADDRESS>:<PORT>"
      path: "secret"
      version: "v1"
      auth:
        tokenSecretRef:
          name: "<YOUR_SECRET_NAME>"
          key: "<YOUR_SECRET_KEY>"
