## Starter Kit prometheus-adapter configuration
## Ref: https://github.com/prometheus-community/helm-charts/tree/prometheus-adapter-3.0.2/charts/prometheus-adapter
##

# Here you tell prometheus-adapter about your Prometheus instance endpoint
prometheus:
  # Make sure to use the right values based on your setup (below value works with Starter Kit).
  # Prometheus URL format is (inside your K8S cluster): http://<prometheus_service_name>.<prometheus_namespace>.svc
  url: http://kube-prom-stack-kube-prome-prometheus.monitoring.svc
  port: 9090
  path: ""

# Number of prometheus-adapter replicas to run.
replicas: 2

# Interval at which to update the cache of available metrics from Prometheus.
metricsRelistInterval: 1m
