name: 'Kubernetes Starter Kit Markdown'

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  lint:
    name: 'Markdown Linting'
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Check out code
      uses: actions/checkout@main

    - name: Lint Code Base
      uses: docker://avtodev/markdown-lint:v1 # fastest way
      with:
        config: './assets/markdown/markdownlint.yml'
        args: "**/*.md"
